version: "2"
services:
  node:
    image: "node:15.5.1"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - "8081:3000"
    restart: always 
    command: bash -c "npm install && npm start"
